default: compile

compile:
	g++ -std=c++11 click_here_for_best_wow_builds.cpp -o out.exe

run:
	g++ -std=c++11 click_here_for_best_wow_builds.cpp -o out.exe
	out.exe

clear:
	rm -rf out.exe output.txt
